apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-shop-dev
  artifacts:
    #- image: us.gcr.io/ticketing-shop-dev/auth
    - image: djolestojanovic/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: djolestojanovic/next-client
      context: next-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.js'
    - image: djolestojanovic/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.js'
    - image: djolestojanovic/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: djolestojanovic/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: djolestojanovic/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.ts'