apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          #image: us.gcr.io/ticketing-shop-dev/auth
          image: djolestojanovic/auth
          env:
            - name: jwt_key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_key

---

#Cluster IP service

apiVersion: v1 
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 4000
      targetPort: 4000