apiVersion: apps/v1
kind: Deployment
metadata: 
  name: next-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-client
  template:
    metadata:
      labels:
        app: next-client
    spec:
      containers:
        - name: auth
          #image: us.gcr.io/ticketing-shop-dev/auth
          image: djolestojanovic/next-client
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NEXT_PUBLIC_STRIPE_PK
              value: "pk_test_51Tgns3C1v2gTabftdPqID9G6l0Xu8DxYFJmVakemynSOnaBQgGAzgX0hWak4WaUqzyrlP7cNNfr4y6eAu38lzcMy00P9W2G2Hy"
            - name: HOST_SERVER
              valueFrom:
                configMapKeyRef:
                  name: next-client-config
                  key: HOST_SERVER


---

#Cluster IP service

apiVersion: v1 
kind: Service
metadata:
  name: next-client-service
spec:
  selector:
    app: next-client
  ports:
    - name: next-client
      protocol: TCP
      port: 3000
      targetPort: 3000